# A 'url' attribute is automatically added for each page
# Keep your homepage mapped to the 'homepage' reserved key

homepage:
    link-text: Go to homepage

consulting:
    short-title: Consulting

'consulting/code-review':
    short-title: Code Review

'consulting/development':
    short-title: Development

'consulting/development/contract/fr':
    short-title: Contrat de prestation
    company_name: '[Nom de votre entreprise]'
    company_person: '[Nom du représentant]'
    company_person_role: '[Rôle du représentant]'
    company_address: '[Adresse de votre entreprise]'
    email_perso1: jonathan.verrecch
    email_perso2: ia@gmail.com
    cycle: 15
    city: '[City]'
    date: '[Date]'

'consulting/code-review/contract':
    short-title: CSS Code Review Agreement

# 'demo/':
#     short-title: ''
# 'demo/':
#     short-title: ''
# 'html5/':
#     short-title: '[FR] '
#
# 'demo/':
#     short-title: ''
# 'demo/':
#     short-title: ''
# 'html5/':
#     short-title: '[FR] '
#

'front-end':
    short-title: 'Front-End Articles'

'html5/html5-page-web-application-web-livre-dunod':
    short-title: "HTML5 : De la page web à l'application web, livre à paraître chez Dunod"

'initializr/initializr-generateur-template-html5-boilerplate':
  short-title: 'Initializr - Un générateur de templates basé sur HTML5 Boilerplate'

'html5/logo-html5-officiel-w3c':
    short-title: 'Le logo HTML5 officiel du W3C'

'css3/introduction-css3':
    short-title: "Introduction au CSS3"

'html5/introduction-html5':
    short-title: "Introduction à l'HTML5"

'html5/conferences-html5-devoxx-2010':
    short-title: 'Les conférences sur HTML5 au Devoxx 2010'

'demo/exemple-application-web-offline-html5-cache-manifest':
    short-title: "Exemple d'application web offline HTML5 avec le cache manifest"
'demo/exemple-application-web-offline-html5-cache-manifest/demo':
    short-title: ''
'html5/tutoriel-application-web-offline-html5-cache-manifest':
    short-title: 'Tutoriel : Une application web offline HTML5 avec le cache manifest'

'demo/exemple-police-css3-font-face-google-font':
    short-title: 'Exemple de police CSS3 avec @font-face et Google Font'
'demo/exemple-police-css3-font-face-google-font/demo':
    short-title: ''
'css3/police-personnalisee-css3-font-face-google-font':
    short-title: 'Une police personnalisée CSS3 avec @font-face ou Google Font'

'demo/exemple-dombre-en-css3-avec-box-shadow':
    short-title: "Exemple d'ombre en CSS3 avec box-shadow"
'demo/exemple-dombre-en-css3-avec-box-shadow/demo':
    short-title: ''
'css3/ombre-css3-box-shadow':
    short-title: 'Les ombres en CSS3 avec box-shadow'

'demo/exemple-geolocalisation-html5-api-google-maps':
    short-title: Exemple API Google Maps
'demo/exemple-geolocalisation-html5-api-google-maps/demo':
    short-title: ''
'html5/tutoriel-api-google-maps-geolocalisation-html5':
    short-title: "Tutoriel sur l'API Google Maps avec la géolocalisation HTML5"

'demo/exemple-geolocalisation-html5':
    short-title: Exemple Géolocalisation HTML5
'demo/exemple-geolocalisation-html5/demo':
    short-title: ''
'html5/tutoriel-geolocalisation-html5':
    short-title: 'Tutoriel de géolocalisation en HTML5'

'initializr/responsive-template':
    short-title: "Initializr: With Great Templates Comes Great Responsivity!"

leafadventure:
    short-title: Leaf Adventure
    url: http://soundcloud.com/leafadventure

'less-css/dont-read-less-css-tutorial-highly-addictive':
    short-title: "DON'T READ this Less CSS Tutorial (Highly Addictive)"

'music-production-lessons':
    short-title: Music Production Lessons

'requirejs/build-simple-client-side-mvc-app-require-js':
    short-title: Build a simple client-side MVC app with RequireJS

resume:
    short-title: Resume

fb:
    short-title: Facebook Redirect

'slides/css-preprocessors':
    short-title: CSS Preprocessors Talk

'slides/todo-zero':
    short-title: Getting Things Done

zeromalist:
    short-title: Minimalism Guidelines

external-links:
    facebook: https://www.facebook.com/stinson.sven
    github: https://github.com/verekia/
    linkedin: https://www.linkedin.com/in/verekia
    twitter: https://twitter.com/verekia


consulting-email: consulting@verekia.com
